### PR TITLE
compress photo of bentley

### PR DESCRIPTION
**Pull request by Penple**
can you believe it? this photo was a whole 16 megabytes????!??!
this means that i cannot embed it into @mattyokan's github profile page
i have reencoded it in the obviously superior jpeg file format which has reduced its size 10x
thank you

### CODE REVIEW

**Comment by tadhgboyle** [comment]
💕😍💝😘❤️💸🥰

**Comment by mattyokan** [comment]
Unacceptable. This threatens the visual quality of Bentley #420, which is art and must be compressed as little as possible.

I disagree fundamentally with the direction of this project and I am refusing to contribute to bentleyBot, effective immediately. Please be more careful about the political statements your project is making.

**Comment by tadhgboyle** [comment]
Feel free to PR 🙂 @mattyokan

**Comment by Penple** [comment]
> Unacceptable. This threatens the visual quality of Bentley #420, which is art and must be compressed as little as possible.
> 
> I disagree fundamentally with the direction of this project and I am refusing to contribute to bentleyBot, effective immediately. Please be more careful about the political statements your project is making.

when?

**Comment by tadhgboyle** [comment]
> Unacceptable. This threatens the visual quality of Bentley #420, which is art and must be compressed as little as possible.
> 
> 
> 
> I disagree fundamentally with the direction of this project and I am refusing to contribute to bentleyBot, effective immediately. Please be more careful about the political statements your project is making.

cope

**Pull request merged**
