### PR TITLE
Add iconic bentley photo

### PR DESCRIPTION
**Pull request by mattyokan**
Adds a useful image.

# Test Cases

Test cases for this change were performed locally:

- ``/bentley 420``
- ``/bentley 85``
- ``/bentley -1``
- ``/bentley 10000``

No regressions detected.

# Business Continuity Plan

In the case of an unexpected event, this commit may be reverted with no harm due to the stateless nature of bentleyBot.

# Next Steps

This PR should be reviewed and edited by maintainers of this fine bot. Thank you.

### CODE REVIEW

**Comment by mattyokan** [comment]
I wish to request a review by @Penple.

**Review by Penple — APPROVED** [review]
LGTM!

**Comment by kev626** [comment]
Okay, Okay, Okay, I need the bently picture count to go up. I can't take this anymore. Everyday I'm checking the bently picture count and it's dipping. Everyday I check the bently picture count, bad bently picture count. I can't take this anymore man. I have become addicted, by a lot. It is what it is but I need the bently picture count to go up. Can devs do something?

**Comment by tadhgboyle** [comment]
$BNTY 🚀

**Comment by tadhgboyle** [comment]
ok

**Pull request merged**
